# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# Check https://fabricmc.net/develop for newer values if a build fails.
minecraft_version=1.16.1
yarn_mappings=1.16.1+build.1
loader_version=0.19.5

# Mod Properties
mod_version=0.1.0
maven_group=net.toolscreen
archives_base_name=toolscreen

# Dependencies
loom_version=1.17-SNAPSHOT
fabric_version=0.42.0+1.16
